# Generated by Django 4.1.2 on 2022-10-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=40)),
                ('Lastname', models.CharField(max_length=40)),
                ('Email', models.EmailField(max_length=40)),
                ('Contact', models.CharField(max_length=40)),
                ('Password', models.CharField(max_length=40)),
            ],
        ),
    ]
